# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f2be82ebc2cddc6da808f6b354967b3a592464a1ed9250873de8e01ed11d36ef1791a6d728effde38c742a0860310f1f41b6cc19300fb9470f90cf567d7cde20

test:
  secret_key_base: 5557b6f00e0799bc7505429e1a3674535eec3ef511af0eb13d65964ef85abb17bcb5851c65b34b7af0d03ac0d889b53ac9b6ae285f6b1d01de0388f05a68526c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
